<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<link rel="stylesheet" href="css/head.css">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
<div class="navbar">
    <nav>
        <ul>
            <li><a href="/">Главная страница</a></li>
            <li><a href="/profile">Личный кабинет</a></li>
            <li><a href="/signIn">Вход</a></li>
            <li><a href="/signUp">Регистрация</a></li>
            <li><a href=""></a></li>
        </ul>
    </nav>
</div>
</html>

